### ISSUE TITLE
Cardav configuration is not saved.

### ISSUE THREAD

**Issue by callmemagnus** [robbertkl/docker-roundcube#12]
Hello,

I try to migrate my setup into your docker container but have an issue.

I can use the native contact management (it saves the contact correctly in the db) but I fail to configure my davcard address book.

I had it working on my previous install.

Symptoms:
- carddav setting fails to be save although the UI save it saved my configuration.
- the sqlite db table carddav_addressbooks stays empty.

I checked that other settings gets saved.

Can you tell how I can investigate this? There are no errors in the docker logs

I also tried to copy over my old configuration, it appears but does not sync.

Thanks in advance.

**Comment by robbertkl** [comment]
Unfortunately, I don't use the carddav plugin part anymore, so I can't tell if it's still working. I kept it in my container for others who are using it. I suggest checking it with the plugin creator ([repo](https://github.com/blind-coder/rcmcarddav)).
