### ISSUE TITLE
Suspected memory leak in roundcube container

### ISSUE THREAD

**Issue by githubbiswb** [robbertkl/docker-roundcube#14]
![GpbSwxYg2e](https://user-images.githubusercontent.com/51446227/65839714-f1916c00-e2dd-11e9-86a1-3ee9483e6efe.png)

The image is from my grafana monitoring server of roundcube's memory resources over the last 30 days. The container doesn't seem to have any issues as the memory rises, but it does rise regardless of people using it or not. A simple restart of the service brings the levels back down. What is really intresting is this issue seems to be escalating more and more quickly each time. You can see in the past it went up a little, and more recently it climbs much faster. 

I am running the sqlite DB, I am using SSL with a Let's Encrpypt cert it has access to. I do also put it through a reverse proxy as well. 

The non commented lines from my roundcube config.inc.php file:
    $config['db_dsnw'] = 'sqlite:////var/www/db/sqlite.db';
    $config['default_host'] = 'ssl://mail.mywebsite.com';
    $config['default_port'] = '993';
    $config['smtp_server'] = 'ssl://mail.mywebsite.com';
    $config['smtp_port'] = '465';
    $config['smtp_user'] = '%u';
    $config['smtp_pass'] = '%p';
    $config['plugins'] = ['archive', 'zipdownload'];
    $config['zipdownload_selection'] = true;

My compose file:
  roundcube:
    image: robbertkl/roundcube
    volumes:
      - /DockerData/email/roundcube/config:/var/www/config
      - /DockerData/email/roundcube/db:/var/www/db
    deploy:
      replicas: 1

I love the work you have done with this and want to assist anyway I am capable of doing to help find the issue. Let me know if you need more info from my side

**Comment by robbertkl** [comment]
Well, I did not write any of the software myself, I just put some packages together with some configuration, so I'm not sure if there's much to fix here.

You could try to see which of the processes is growing in memory size by looking at `top` from inside your container:

```
docker exec -it YOUR_CONTAINER top
```

**Comment by githubbiswb** [comment]
From what I am seeing so far it is the php5-fpm process that keeps growing. I did another scale down and up and those memory numbers came way down, in fact it is running one less php5-fpm process when it restarts. The other processes seem to be the same in memory usage, which the php5-fpm ones growing over time.

**Comment by robbertkl** [comment]
Does it keep on growing indefinitely? Or does it stabilize somewhere?

What's the usage of your roundcube instance? Perhaps your fpm config can be tweaked to better accommodate your usage.

**Comment by githubbiswb** [comment]
It continues to grow indefinitely. I have also noticed the php5-fpm memory grows only on the processes that the www-data user is running. The one from root stays consistent. 

![lX7AeyDs0n](https://user-images.githubusercontent.com/51446227/66754182-6a0e3600-ee63-11e9-849a-faae86734298.png)

![iOnIW2ifBG](https://user-images.githubusercontent.com/51446227/66754204-72667100-ee63-11e9-947a-c4a917b140a8.png)

**Comment by robbertkl** [comment]
I'm actually going to discontinue this Docker image in the near future, since roundcube has [an official Docker image](https://hub.docker.com/r/roundcube/roundcubemail), which they didn't have at the time I created this.

They have both fpm and standalone Apache images. I'd advise to start looking into switching to this. It should be fairly easy: just some configuration and perhaps install some of the additional plugins (if you even use them).

**Comment by githubbiswb** [comment]
Sounds good, thank you for your time
