### ISSUE TITLE
credencial? password?

### ISSUE THREAD

**Issue by lucenarenato** [robbertkl/docker-roundcube#15]
credencial? password?

**Comment by lucenarenato** [comment]
Can you configure a credential or authentication to access with username and password?

**Comment by robbertkl** [comment]
Hi @lucenarenato, Roundcube authenticates with your mail server (IMAP / POP3), so you need to log in with your e-mail credentials. Roundcube does not have its own authentication mechanism.

Hope this helps.

**Comment by lucenarenato** [comment]
Ok, talks
