### ISSUE TITLE
Default user and password

### ISSUE THREAD

**Issue by tarantegui** [robbertkl/docker-roundcube#2]
Hi,

I have not found the documentation to obtain the user name and password by default. I have not found how to change them. Could you improve the documentation of container?

Thank you

**Comment by robbertkl** [comment]
There is no default username/password. Roundcube will connect to an IMAP server and authenticates with it. Roundcube does not run standalone and does not have its own password database. See the section "Environment variables" in the README on how to configure the IMAP server to use.

Does this clarify things?

**Comment by tarantegui** [comment]
Yes it does, thank you.
