### ISSUE TITLE
How to set ROUNDCUBE_DEFAULT_HOST to blank?

### ISSUE THREAD

**Issue by marceloschmidt** [robbertkl/docker-roundcube#3]
How can I set the ROUNDCUBE_DEFAULT_HOST environment variable to a blank string, so that it will ask me what server I want to connect to?

TIA

**Comment by robbertkl** [comment]
I'm not sure if it will ask you the server, but you can use`-e ROUNDCUBE_DEFAULT_HOST=` in your `docker run` command to make it a blank string.
