### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by gitgc** [robbertkl/docker-roundcube#5]
Hi Robert,

I was interested in using this image in a development environment, is there any chance you can publish tagged releases in addition to 'latest'? I hate not being able to version pin dependencies, in case a breaking change hits latest and ruins our builds etc.

**Comment by robbertkl** [comment]
Hi @gitgc,

Unfortunately, that would mean I have to commit/tag every roundcube release manually, which I'm unable to maintain in the long run.

**Comment by gitgc** [comment]
Ah, no worries, thanks for the response.
