### ISSUE TITLE
mount persistent volume

### ISSUE THREAD

**Issue by maxhoheiser** [robbertkl/docker-roundcube#6]
hi i want to use docker-compose with your image, where do I have to mount the persistent folder inside the roundcube container?

**Comment by robbertkl** [comment]
Check the `Dockerfile`, it's right there:

```
VOLUME /var/www/db
```

Good luck!

**Comment by mad1993max** [comment]
just one question how does the file passt with ROUNDCUBE_USER_FILE should look like?

`username:password`
`username2:password2` ?

**Comment by robbertkl** [comment]
@mad1993max Well, the ROUNDCUBE_USER_FILE is only useful if you're also using (the same) password file for your mail server.

Roundcube just authenticates to your mailserver through IMAP, so the user file isn't used for that. My mail server (dovecot, see https://github.com/robbertkl/docker-mail) uses a file as user db, and I mount this same file into my Roundcube container, to allow changing your user password from within Roundcube.

The password file for dovecot uses:

```
username:{SSHA}hash
username2:{SSHA}hash2
```
