### ISSUE TITLE
roundcube 1.3 breaks image

### ISSUE THREAD

**Issue by heinemml** [robbertkl/docker-roundcube#7]
Since the version on hub now seems to be updated to use roundcube 1.3 my install is broken.

Short analysis: there seems to be a missing jquery and probably other js libraries.

It looks like since 1.3 roundcube uses a `jsdeps.json` file which is read by `bin/install-jsdeps.sh`
When I try to execute this script manually it fails due to a missing unzip binary.

**Comment by heinemml** [comment]
I was able to fix it manually from inside the container:

```
apt update
apt install unzip
apt install file
bin/install-jsdeps.sh
```

So I guess the Dockerfile needs an update.

**Comment by robbertkl** [comment]
Should be fixed now! Thanks for reporting.
