### ISSUE TITLE
image cannot be built

### ISSUE THREAD

**Issue by sholl** [robbertkl/docker-roundcube#9]
Since I need to change some plugin-config-parameters I am in the need to rebuild the image.
Though it does not build cleanly:
` docker build -t sholl/roundcube:dev --build-arg PLUGINS_DB_PW=<snip> .`

`Step 7/15 : RUN VERSION=`latestversion roundcube/roundcubemail`     && rm -rf *     && pwd     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer
 ---> Running in 9387e01421bd
/var/www
fatal: destination path '.' already exists and is not an empty directory.
The command '/bin/sh -c VERSION=`latestversion roundcube/roundcubemail`     && rm -rf *     && pwd     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer' returned a non-zero code: 128
`

**Comment by robbertkl** [comment]
It builds fine here, and on Docker Hub as well; just tested another build and it completed without failure.

Perhaps it's caused by changes you've made? Can you try building the original repo without any changes, by just running `make`?

**Comment by sholl** [comment]
mhh, strange, just did a fresh clone from GH and executed 'make' and it did not succeed:
``` shell
 make
docker build --rm --tag=robbertkl/roundcube .
Sending build context to Docker daemon   68.1kB
Step 1/14 : FROM robbertkl/php
 ---> a7099a2960e8
Step 2/14 : MAINTAINER Robbert Klarenbeek <robbertkl@renbeek.nl>
 ---> Using cache
 ---> 3fa532e25fe6
Step 3/14 : ENV DOCUMENT_ROOT /var/www/public_html
 ---> Using cache
 ---> 2b931e65109a
Step 4/14 : WORKDIR ${DOCUMENT_ROOT}/..
 ---> Using cache
 ---> c2fb7e77a2a4
Step 5/14 : RUN VERSION=`latestversion roundcube/roundcubemail`     && rm -rf *     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer
 ---> Running in c02e80c77f6a
fatal: destination path '.' already exists and is not an empty directory.
The command '/bin/sh -c VERSION=`latestversion roundcube/roundcubemail`     && rm -rf *     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer' returned a non-zero code: 128
Makefile:6: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 128
`

**Comment by robbertkl** [comment]
Can you insert ` && ls -la` after the `rm -rf *` to see why the directory is not empty?

**Comment by sholl** [comment]
Here is the output what I got:
```shell
Step 2/14 : MAINTAINER Robbert Klarenbeek <robbertkl@renbeek.nl>
 ---> Running in e9d37ace3b21
 ---> 12ba2de1d7bf
Removing intermediate container e9d37ace3b21
Step 3/14 : ENV DOCUMENT_ROOT /var/www/public_html
 ---> Running in 225cb2e27adf
 ---> c369ef7ef938
Removing intermediate container 225cb2e27adf
Step 4/14 : WORKDIR ${DOCUMENT_ROOT}/..
 ---> 5cd7e6412eb5
Removing intermediate container 770d5f8851c2
Step 5/14 : RUN VERSION=`latestversion roundcube/roundcubemail`     && rm -rf * && ls -al     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer
 ---> Running in 4099dddba052
ls: cannot access html: No such file or directory
ls: cannot access index.php: No such file or directory
total 0
drwxr-xr-x 1 root root 22 Sep 13 18:23 .
drwxr-xr-x 1 root root 16 Sep 13 11:20 ..
?????????? ? ?    ?     ?            ? html
?????????? ? ?    ?     ?            ? index.php
The command '/bin/sh -c VERSION=`latestversion roundcube/roundcubemail`     && rm -rf * && ls -al     && git clone --branch ${VERSION} --depth 1 https://github.com/roundcube/roundcubemail.git .     && rm -rf .git installer' returned a non-zero code: 1

```

**Comment by robbertkl** [comment]
Wow, never seen that before. What environment are you running in? OS, docker version, etc.

**Comment by sholl** [comment]
OK, here you are:
Host Debian stretch (stable)
Docker info:
```
...
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
...
```
after googling arround I see that the needed `d_type`-Support ist missing. I will recreate the storage partition and report back. Maybe this is the culprit? Never had any problems though.

**Comment by sholl** [comment]
so, recreating the filesystem with the d_type-Support cures the strange problem. Thanks for your pointers 👍
